---
- name: test block / conditional
  hosts: rhel
  become: yes

  tasks:
    - name: some task
      block:
        - name: task inside block, fails
          debug:
            msg: "Some task inside block, which fails"
        - name: failed task
          command: /bin/foo

      rescue:
        - name: rescue task
          debug:
            msg: "Some task inside rescue"
