---
- name: test common file module uses
  hosts: rhel2
  become: yes

  tasks:
    - name: add content to /etc/foo.conf 
      blockinfile:
        path: /etc/foo.conf
        insertafter: '#comment'
        content: |
          This is inserted aaaa
          This is inserted bbbb


