---
- name: create partition with parted
  hosts: rhel
  become: yes

  tasks:
  - name: get disk size of sdb
    parted:
      device: /dev/sdb
      unit: GiB
    register: sdb_info
  - name: create a 2G partition using parted
    parted:
      device: /dev/sdb
      state: present
      number: 1
      part_end: 2GB
    when: sdb_info.disk.size > 8 
...
