---
- name: create an ssh key
  hosts: rhel2
  become: yes

  tasks:
    - name: create an ssh key
      user:
        name: user1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_my_rsa

